{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka-backup-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-backup-operator.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kafka-backup-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kafka-backup-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}